---

# Theme
remote_theme: epidrome/cover-card@main
#remote_theme: kgbe/tests@main


# Title and tag line
title: endlessrockets
description: social media
avatar: transparent-picture.png
background: tyreek-hill.gif


# Online profiles
#facebook: 'myfacebook'
#twitter: 'endless_rockets'
tiktok: 'endlessrockets'
instagram: 'realendlessrockets'
#pinterest: 'mypinterest'
youtube: 'RealEndlessRockets'
#github-user: 'endlessrockets'
#gitlab-user: ''
#codepen: ''
steam: '76561198447052378'
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
reddit: 'endlessrockets'
#email: 'hello@example.com'
#messenger: 'myfbchat'
discord: 'vWCXAgvTFR'
roblox: '286790524'
telegram: 'endlessrockets'
#twitter: 'endless_rockets'
spotify: 'h067x9uq92ipmhrf6jdqct9in'




social-links-order:
  - youtube
  - tiktok
  - instagram
  - discord
  - telegram
  - reddit
  - spotify
  - steam
  - roblox





  
# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**




social-links:
  - name: youtube
    url-pattern: youtube.com/@__USERNAME__
  - name: tiktok
    url-pattern: www.tiktok.com/@__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-tiktok
  - name: instagram
    url-pattern: instagram.com/__USERNAME__/profile
    url-scheme: https://
    icon-class: fab fa-2x fa-instagram
  - name: discord
    url-pattern: discord.gg/__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-discord
  - name: steam
    url-pattern: steamcommunity.com/profiles/__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-steam
  - name: x
    url-pattern: x.com/__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-twitter
  - name: reddit
    url-pattern: reddit.com/user/__USERNAME__
  - name: telegram
    url-pattern: telegram.me/__USERNAME__
  - name: spotify
    url-pattern: open.spotify.com/user/__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-spotify
  - name: roblox
    url-pattern: roblox.com/users/__USERNAME__/profile
    url-scheme: https://
    icon-class: fas fa-2x fa-user




